/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RederiImport } from './routes/rederi'
import { Route as RanksImport } from './routes/ranks'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const RederiRoute = RederiImport.update({
  path: '/rederi',
  getParentRoute: () => rootRoute,
} as any)

const RanksRoute = RanksImport.update({
  path: '/ranks',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/ranks': {
      preLoaderRoute: typeof RanksImport
      parentRoute: typeof rootRoute
    }
    '/rederi': {
      preLoaderRoute: typeof RederiImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  RanksRoute,
  RederiRoute,
])

/* prettier-ignore-end */
